apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rs-dev
  name: my-app-service
  labels:
    app: my-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-service
  template:
    metadata:
      labels:
        app: my-app-service
    spec:
      containers:
      - name: my-app-service
        image: 192.168.214.154/cp/my-app:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8109
---
apiVersion: v1
kind: Service
metadata:
  namespace: rs-dev
  name: my-app-service
  labels:
    app: my-app-service
spec:
  ports:
    - port: 8109
      targetPort: 8109
      nodePort: 30207
  selector:
    app: my-app-service
  type: NodePort
